// import { NextIntlClientProvider } from "next-intl";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/organisms/Header/Header";
import Footer from "@/components/organisms/Footer/Footer";
import styles from "./layout.module.scss";
// import { getMessages } from "next-intl/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Costco",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: // params,
Readonly<{
  children: React.ReactNode;
  // params: { locale: string };
}>) {
  // const messages = await getMessages();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <NextIntlClientProvider
        //  messages={messages}
         locale="en"
     > */}
        <div className="flex flex-col">
          <div>
            <Header />
          </div>
          <div className="m-1">{children}</div>
          <div>
            <Footer />
          </div>
        </div>
        {/* </NextIntlClientProvider> */}
      </body>
    </html>
  );
}
