name: Deploy Next.js UI to GKE

on:
  push:
    branches:
      - main  # Or whichever branch you want to trigger deployment

jobs:
  deploy:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Authenticate to GCP using the service account
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Step 3: Setup gcloud CLI with kubectl component
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: 'kubectl'

      # Step 4: Configure kubectl to use the GKE cluster
      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials my-gke-cluster \
            --zone ${{ secrets.GCP_ZONE }} \
            --project ${{ secrets.GCP_PROJECT }}

      # Step 5: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/nextjs-ui:$GITHUB_SHA .

      # Step 6: Push Docker image to GCR
      - name: Push to GCR
        run: |
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/nextjs-ui:$GITHUB_SHA

      # Step 7: Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl set image deployment/nextjs-ui-deployment nextjs-ui=gcr.io/${{ secrets.GCP_PROJECT }}/nextjs-ui:$GITHUB_SHA -n dev-cosco
