name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Validate gcloud auth
      run: gcloud auth list

    - name: Authenticate kubectl with GKE
      run: |
        gcloud container clusters get-credentials my-gke-cluster \
          --zone ${{ secrets.GCP_ZONE }} \
          --project ${{ secrets.GCP_PROJECT }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Build and Push Docker Image
      run: |
        IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/nextjs-ui:${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    - name: Create Namespace if not exists
      run: |
        kubectl get namespace dev-cosco || kubectl create namespace dev-cosco

    - name: Deploy to GKE
      run: |
        # Substitute the dynamic image tag in deployment.yaml
        sed "s|gcr.io/YOUR-GCP-PROJECT-ID/nextjs-ui:latest|${IMAGE}|" k8s/deployment.yaml | kubectl apply -f -
