name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Authenticate to GKE
      run: |
        gcloud container clusters get-credentials my-gke-cluster \
          --zone ${{ secrets.GCP_ZONE }} \
          --project ${{ secrets.GCP_PROJECT }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Build and Push Docker Image
      run: |
        IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/nextjs-ui:${{ github.sha }}
        docker build -t $IMAGE .
        docker push $IMAGE
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    - name: Deploy to GKE
      run: |
        kubectl create namespace dev-cosco --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f k8s/deployment.yaml \
          --namespace dev-cosco \
          --record=true
